### ISSUE TITLE
Assess feasibility of including Kelly Wrighton datasets - user stories

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#29]
This issue is to track the user stories associated with including the datasets from Kelly Wrighton

**Comment by pvangay** [comment]
@mslarae13 and I met with Reb Daly from Kelly's group today to discuss linking their NMR data. They are interested but cited that this data is not in myEMSL and therefore not linkable. They also cited that it was difficult to sort out the data/sample/project relationships for this data. This issue is related to https://github.com/microbiomedata/NMDC_Planning/issues/30 and therefore is now a technical issue that needs to be sorted out. Will close this issue.

**Comment by pvangay** [comment]
We still need to sort out the technical issues related to making their NMR data from the same proposal available (#30) but Kelly's group expressed interest in making another carbon shale dataset available in the NMDC (this is a larger proposal that took place after their first proposal, and they say it has more interesting data).

- [ ] @dehays can you look into JGI proposal #1931 and assess the data that's there? there should be metaG and metaT (and other datatypes) available.

- [ ] @jagadishcs can you check JGI proposal #1931 in GOLD and make sure the metadata there is curated/complete?

- [ ] @mslarae13 @corilo can you look into EMSL proposal #50214 and confirm the metaB data they have is something we can support?

**Comment by pvangay** [comment]
Sync's with @mslarae13 and @corilo to assess the EMSL data. Had some difficulty finding it in NEXUS - requested additional info on the metaB type. Currently had a few questions for Reb. waiting on her to get back to us so they can find the data.

Also sent email to @jagadishcs to review metadata in GOLD - he will update here when he's finished.

**Comment by pvangay** [comment]
Update from @dehays that metadata for this project will be included in GOLD export.

Blocked - waiting on collaborator to help with sorting out metaB data.

**Comment by ssarrafan** [comment]
Moved from June Sprint to July Sprint per Pajau's request

**Comment by ssarrafan** [comment]
_Morning! could we move this one to the backlog? 
I just realized that this one has to do with getting more data into the system. and Reb had asked whether we could revisit it after the summer because theyre just swamped with fieldwork at the moment._

Note from Pajau. Moving to backlog.
