### ISSUE TITLE
Process for metrics tracking

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#84]
Process for metrics tracking finalized, updated
More details at https://docs.google.com/spreadsheets/d/1NEl8RuKffuvUm_Q4MLYcYMqSEDgkW15f2eyHttJfhlc/edit#gid=0

**Comment by ssarrafan** [comment]
@mar-rudolph and I met today and the next steps for this will be:

- [ ] Meet with Kjiersten (8/2) on the technical metrics
- [ ] Follow up with tech sync as needed
- [ ] Get ideas from presentations from the JAWS team on monitoring and dashboards at tech syncs
- [ ] Make a decision about CRM 

Moving this to the August sprint.
